name: Publish to GH Pages
on:
  push:
    branches:
      - main
      - init
#TODO: run the index.html on a website
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
